#>
#include <allegro5/allegro.h>
<#
(module allegro *
        (import scheme chicken bind foreign foreigners)

        (include "base")
        (include "system")
        (include "config")
        (include "path")
        (include "file")
        (include "utf8")
        ;(include "memory")
        ;(include "debug")
        (include "error")
        (include "altime")
        (include "events")
        (include "mouse")
        ;(include "timer")
        ;(include "keyboard")
        ;(include "joystick")
        ;(include "threads")
        ;(include "display")
        ;(include "transformations")
        ;(include "bitmap_io")
        ;(include "bitmap")
        ;(include "tls")
        ;(include "file")
        ;(include "fshook")
        ;(include "path")
        ;(include "fmaths")
        ;(include "config")
)
